name: Build EXE Portable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --force

      - name: Install Electron Builder
        run: npm install electron-builder --save-dev --force

      - name: Build portable exe (Windows 32-bit)
        run: npx electron-builder --win portable --ia32

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-portable
          path: dist/*
